spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Jiazhiyu281110
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.gyofu.entity